### ISSUE TITLE
Incompatibilty with modern fix

### ISSUE THREAD

**Issue by Killeronduty1** [Fayenora/Robotics#1] opened 2024-09-21 17:29 UTC
the mod crashes on startup with modern fix in mods list

start Minecraft 1.20.1 with geckolib and norabotics with modern fix installed

no crash log available

**Comment by Fayenora** [comment] 2024-09-21 19:57
Thanks for the report, I was able to reproduce the issue. 
The incompatibility was due to Robotics attempt to overwrite a vanilla method when it need'nt to. I rewrote the part so compatability with other mods should also have increased. 
I can start the game alongside ModernFix now and the issue should be fixed. The fix should already be available on modrinth

**Comment by Killeronduty1** [comment] 2024-09-21 23:37
awesome thanks!

**Comment by Killeronduty1** [comment] 2024-09-21 23:40
hey, I got a question. my info pad for the mod doesn't seem to display any info is this intended?
![2024-09-21_17 38 43](https://github.com/user-attachments/assets/d82b67e6-504d-499a-8fbf-a43661f02759)

**Comment by Killeronduty1** [comment] 2024-09-21 23:40
![2024-09-21_17 40 21](https://github.com/user-attachments/assets/a7d93f54-3ee7-4047-8792-b52e0e8e3bfb)

**Comment by Fayenora** [comment] 2024-09-22 17:28
That's definetely not supposed to happen, should be fixed it with the new update

**Closed as completed** 2024-09-22 17:33 UTC
Labels: bug, fixed
